apiVersion: v1
kind: Service
metadata:
  name: shopsmart-client
  namespace: shopsmart
  labels:
    app: shopsmart-client
spec:
  type: LoadBalancer
  selector:
    app: shopsmart-client
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
